<?php

namespace App\Console\Commands;

use App\Models\TalentBuild;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Dumps every admin-default TalentBuild's picks (PvE + PvP) into the committed
 * data/spelldata/default-talent-builds.txt — the counterpart to wow:apply-default-talents.
 *
 * Why this exists: TalentBuild selections were never captured in any committed file, unlike
 * baseline-spec-overrides.txt/cc-synergies-overrides.txt for spell data — they only ever lived
 * in whichever environment's DB an admin last curated them in (via /admin/talent-builds,
 * wow:import-murlok-defaults, or a Blizzard talent-string import). A fresh machine (or a wiped
 * production DB) had genuinely no way to reproduce them without re-running one of those
 * per-spec, per-machine curation steps by hand — the exact gap surfaced 2026-08-19 when
 * comparing local vs. production admin-default builds directly and finding real differences.
 *
 * Matched by spell_id + rank, never raw talent_node_id/chosen_entry_id — those are internal
 * auto-increment PKs, not guaranteed stable across a re-import (confirmed the hard way this same
 * session: two environments' node IDs for the identical talent tree can differ). spell_id alone
 * isn't always enough either: a multi-rank node's several ranks commonly share one spell_id
 * (e.g. Improved Fade), so rank is what disambiguates which specific entry was chosen — the
 * same two-part key TalentBuildChoice.rank already stores for exactly this reason.
 *
 * Run this on whichever environment currently has the builds you want to become the new
 * baseline, then commit the resulting file. wow:apply-default-talents is what a fresh
 * environment actually runs to reproduce them.
 */
class ExportDefaultTalents extends Command
{
    protected $signature = 'wow:export-default-talents {--path= : Override the output path (used by tests)}';

    protected $description = 'Exports every admin-default TalentBuild (PvE + PvP picks) to a committed file, so wow:apply-default-talents can reproduce them on any environment.';

    public function handle(): int
    {
        $path = $this->option('path') ?: base_path('data/spelldata/default-talent-builds.txt');

        $builds = TalentBuild::where('is_default', true)
            ->with([
                'specialization.gameClass',
                'choices.chosenEntry.spell',
                'pvpChoices.pvpTalent.spell',
            ])
            ->get()
            ->filter(fn (TalentBuild $b) => $b->specialization && $b->specialization->gameClass)
            ->sortBy(fn (TalentBuild $b) => $b->specialization->gameClass->slug.':'.$b->specialization->slug);

        $lines = [
            '# Admin-default TalentBuild picks — generated by wow:export-default-talents.',
            '# Applied by wow:apply-default-talents — deliberately NOT wired into import:spelldata',
            '# automatically, so an admin actively re-curating a live build via /admin/talent-builds',
            '# does not get silently reverted by an unrelated routine spell-data re-import.',
            '# Re-export after any deliberate build change you want to become the new baseline',
            '# for fresh environments.',
            '#',
            '# Format: class_slug | spec_slug | kind(pve|pvp) | spell_id | rank | name (comment only)',
            '#   - pve rows: rank disambiguates a multi-rank node sharing one spell_id across ranks.',
            '#   - pvp rows: rank is always blank (PvP talents have no rank concept).',
            '# Regenerated wholesale each export — do not hand-edit, re-export instead.',
        ];

        $buildCount = 0;
        $choiceCount = 0;

        foreach ($builds as $build) {
            $spec = $build->specialization;
            $class = $spec->gameClass;
            $buildCount++;

            $lines[] = '';
            $lines[] = "# {$class->name} / {$spec->name} (exported ".now()->toDateString().')';

            foreach ($build->choices->sortBy(fn ($c) => $c->chosenEntry?->spell?->display_name ?? '') as $choice) {
                $spell = $choice->chosenEntry?->spell;

                if (!$spell) {
                    continue;
                }

                $lines[] = "{$class->slug} | {$spec->slug} | pve | {$spell->spell_id} | {$choice->rank} | {$spell->display_name}";
                $choiceCount++;
            }

            foreach ($build->pvpChoices->sortBy(fn ($c) => $c->pvpTalent?->spell?->display_name ?? '') as $pvpChoice) {
                $spell = $pvpChoice->pvpTalent?->spell;

                if (!$spell) {
                    continue;
                }

                $lines[] = "{$class->slug} | {$spec->slug} | pvp | {$spell->spell_id} | | {$spell->display_name}";
                $choiceCount++;
            }
        }

        File::put($path, implode("\n", $lines)."\n");

        $this->info("Exported {$buildCount} default build(s), {$choiceCount} total picks, to {$path}");

        return self::SUCCESS;
    }
}
